language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nathangarrihy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nathangarrihy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-west-1-496594881156"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY