language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nathangarrihy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nathangarrihy/docker-react npm run test